import tkinter as tk
from tkinter import ttk
from tkinter import filedialog
import random
# random.randint(1, 4)
def calcular_estadisticas(valoracion, posicion):
    # Lógica para calcular estadísticas en función de la valoración y la posición
    if posicion == "DEL":
        ataque = random.randint(round(valoracion * 0.9), valoracion + 8)
        defensa = round(valoracion * 0.48)
        estabilidad = random.randint(round(valoracion * 0.9), valoracion + 5)
        resistencia = random.randint(round(valoracion * 0.9), valoracion)
        agilidad = random.randint(round(valoracion * 0.9), valoracion + 4)
        velocidad_maxima = random.randint(round(valoracion * 0.8), valoracion + 3)
        aceleracion = random.randint(round(valoracion * 0.8), valoracion + 1)
        respuesta = random.randint(round(valoracion * 0.9), valoracion)
        precision_regate = random.randint(round(valoracion * 0.8), valoracion + 1)
        velocidad_regate = random.randint(round(valoracion * 0.8), valoracion + 3)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion - 3)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion - 3)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion - 4)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion - 4)
        precision_disparo = random.randint(round(valoracion * 0.9), valoracion + 5)
        potencia_disparo = random.randint(round(valoracion * 0.9), valoracion + 7)
        tecnica_disparo = random.randint(round(valoracion * 0.9), valoracion + 6)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 8)
        efecto = random.randint(round(valoracion * 0.9), valoracion)
        cabezazo = random.randint(round(valoracion * 0.9), valoracion + 8)
        salto = round(valoracion * 0.83)
        tecnica = random.randint(round(valoracion * 0.8), valoracion)
        agresividad = random.randint(round(valoracion * 0.9), valoracion + 8)
        mentalidad = random.randint(round(valoracion * 0.9), valoracion + 8)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.85)
        estabilidad_soltura = random.randint(1,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "EXT":
        ataque = random.randint(round(valoracion * 0.88), valoracion + 4)
        defensa = round(valoracion * 0.53)
        estabilidad = random.randint(round(valoracion * 0.9), valoracion + 3)
        resistencia = random.randint(round(valoracion * 0.9), valoracion + 4)
        agilidad = random.randint(round(valoracion * 0.9), valoracion + 1)
        velocidad_maxima = random.randint(round(valoracion * 0.9), valoracion + 6)
        aceleracion = random.randint(round(valoracion * 0.9), valoracion + 6)
        respuesta = random.randint(round(valoracion * 0.9), valoracion + 2)
        precision_regate = random.randint(round(valoracion * 0.9), valoracion + 7)
        velocidad_regate = random.randint(round(valoracion * 0.9), valoracion + 7)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion - 1)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion - 1)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion - 2)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion - 2)
        precision_disparo = random.randint(round(valoracion * 0.9), valoracion - 2)
        potencia_disparo = random.randint(round(valoracion * 0.9), valoracion - 3)
        tecnica_disparo = random.randint(round(valoracion * 0.9), valoracion)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 6)
        efecto = random.randint(round(valoracion * 0.9), valoracion)
        cabezazo = random.randint(round(valoracion * 0.6), valoracion - 10)
        salto = random.randint(round(valoracion * 0.68), (valoracion - 12))
        tecnica = random.randint(round(valoracion * 0.8), valoracion + 5)
        agresividad = random.randint(round(valoracion * 0.9), valoracion)
        mentalidad = random.randint(round(valoracion * 0.9), valoracion)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.85)
        estabilidad_soltura = random.randint(1,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "MP":
        ataque = random.randint(round(valoracion * 0.88), valoracion + 3)
        defensa = round(valoracion * 0.615)
        estabilidad = random.randint(round(valoracion * 0.9), valoracion)
        resistencia = random.randint(round(valoracion * 0.9), valoracion - 2)
        agilidad = random.randint(round(valoracion * 0.9), valoracion + 4)
        velocidad_maxima = random.randint(round(valoracion * 0.9), valoracion - 2)
        aceleracion = random.randint(round(valoracion * 0.9), valoracion - 3)
        respuesta = random.randint(round(valoracion * 0.9), valoracion - 1)
        precision_regate = random.randint(round(valoracion * 0.9), valoracion + 3)
        velocidad_regate = random.randint(round(valoracion * 0.9), valoracion + 5)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 3)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 3)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 1)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 1)
        precision_disparo = random.randint(round(valoracion * 0.9), valoracion + 2)
        potencia_disparo = random.randint(round(valoracion * 0.9), valoracion)
        tecnica_disparo = random.randint(round(valoracion * 0.9), valoracion + 2)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 5)
        efecto = random.randint(round(valoracion * 0.9), valoracion - 5)
        cabezazo = random.randint(round(valoracion * 0.8), round(valoracion * 0.9))        
        salto = round(valoracion * 0.7)
        tecnica = random.randint(round(valoracion * 0.8), valoracion + 2)
        agresividad = random.randint(round(valoracion * 0.9), valoracion - 2)
        mentalidad = random.randint(round(valoracion * 0.9), valoracion - 4)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.85)
        estabilidad_soltura = random.randint(1,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "MC":
        ataque = random.randint(round(valoracion * 0.85), valoracion + 4)
        defensa = random.randint(round(valoracion * 0.85), valoracion)
        estabilidad = random.randint(round(valoracion * 0.89), valoracion - 3)
        resistencia = random.randint(round(valoracion * 0.93), valoracion + 5)
        agilidad = random.randint(round(valoracion * 0.9), valoracion)
        velocidad_maxima = random.randint(round(valoracion * 0.8), valoracion - 6)
        aceleracion = random.randint(round(valoracion * 0.8), valoracion - 6)
        respuesta = random.randint(round(valoracion * 0.9), valoracion - 1)
        precision_regate = random.randint(round(valoracion * 0.89), valoracion + 3)
        velocidad_regate = random.randint(round(valoracion * 0.89), valoracion + 3)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 4)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 4)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 3)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 3)
        precision_disparo = random.randint(round(valoracion * 0.85), valoracion - 5)
        potencia_disparo = random.randint(round(valoracion * 0.85), valoracion - 2)
        tecnica_disparo = random.randint(round(valoracion * 0.87), valoracion - 5)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 5)
        efecto = random.randint(round(valoracion * 0.9), valoracion - 5)
        cabezazo = random.randint(round(valoracion * 0.8), round(valoracion * 0.9))        
        salto = random.randint(round(valoracion * 0.7), round(valoracion * 0.9))    
        tecnica = random.randint(round(valoracion * 0.85), valoracion + 7)
        agresividad = random.randint(round(valoracion * 0.88), valoracion - 4)
        mentalidad = random.randint(round(valoracion * 0.7), valoracion + 6)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.9)
        estabilidad_soltura = random.randint(5,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "CAR":
        ataque = random.randint(round(valoracion * 0.86), valoracion - 3)
        defensa = random.randint(round(valoracion * 0.86), valoracion - 3)
        estabilidad = random.randint(round(valoracion * 0.89), valoracion - 5)
        resistencia = random.randint(round(valoracion * 0.93), valoracion + 7)
        agilidad = random.randint(round(valoracion * 0.9), valoracion - 4)
        velocidad_maxima = random.randint(round(valoracion * 0.79), valoracion + 3)
        aceleracion = random.randint(round(valoracion * 0.79), valoracion + 6)
        respuesta = random.randint(round(valoracion * 0.9), valoracion - 2)
        precision_regate = random.randint(round(valoracion * 0.83), valoracion - 2)
        velocidad_regate = random.randint(round(valoracion * 0.83), valoracion - 2)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion - 2)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion - 2)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion - 3)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion - 3)
        precision_disparo = random.randint(round(valoracion * 0.85), valoracion - 6)
        potencia_disparo = random.randint(round(valoracion * 0.85), valoracion - 6)
        tecnica_disparo = random.randint(round(valoracion * 0.87), valoracion - 2)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 3)
        efecto = random.randint(round(valoracion * 0.9), valoracion - 3)
        cabezazo = random.randint(round(valoracion * 0.68), round(valoracion * 0.8))        
        salto = random.randint(round(valoracion * 0.697), round(valoracion * 0.8))    
        tecnica = random.randint(round(valoracion * 0.88), valoracion - 2)
        agresividad = random.randint(round(valoracion * 0.88), valoracion)
        mentalidad = random.randint(round(valoracion * 0.86), valoracion + 6)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.9)
        estabilidad_soltura = random.randint(4,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "MCD":
        ataque = random.randint(round(valoracion * 0.8), valoracion - 7)
        defensa = random.randint(round(valoracion * 0.85), valoracion + 2)
        estabilidad = random.randint(round(valoracion * 0.89), valoracion - 3)
        resistencia = random.randint(round(valoracion * 0.93), valoracion + 5)
        agilidad = random.randint(round(valoracion * 0.9), valoracion - 4)
        velocidad_maxima = random.randint(round(valoracion * 0.79), valoracion - 4)
        aceleracion = random.randint(round(valoracion * 0.79), valoracion - 4)
        respuesta = random.randint(round(valoracion * 0.9), valoracion - 6)
        precision_regate = random.randint(round(valoracion * 0.83), valoracion)
        velocidad_regate = random.randint(round(valoracion * 0.83), valoracion)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 2)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 2)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 5)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 5)
        precision_disparo = random.randint(round(valoracion * 0.85), valoracion - 6)
        potencia_disparo = random.randint(round(valoracion * 0.85), valoracion - 6)
        tecnica_disparo = random.randint(round(valoracion * 0.87), valoracion - 2)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 3)
        efecto = random.randint(round(valoracion * 0.9), valoracion - 3)
        cabezazo = random.randint(round(valoracion * 0.7), round(valoracion * 0.9))        
        salto = random.randint(round(valoracion * 0.7), round(valoracion * 0.9))    
        tecnica = random.randint(round(valoracion * 0.85), valoracion + 2)
        agresividad = random.randint(round(valoracion * 0.88), valoracion - 4)
        mentalidad = random.randint(round(valoracion * 0.7), valoracion + 6)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.9)
        estabilidad_soltura = random.randint(4,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "LAT":
        ataque = random.randint(round(valoracion * 0.8), valoracion - 7)
        defensa = random.randint(round(valoracion * 0.85), valoracion + 2)
        estabilidad = random.randint(round(valoracion * 0.89), valoracion - 3)
        resistencia = random.randint(round(valoracion * 0.93), valoracion + 5)
        agilidad = random.randint(round(valoracion * 0.9), valoracion - 4)
        velocidad_maxima = random.randint(round(valoracion * 0.79), valoracion - 4)
        aceleracion = random.randint(round(valoracion * 0.79), valoracion - 4)
        respuesta = random.randint(round(valoracion * 0.9), valoracion - 6)
        precision_regate = random.randint(round(valoracion * 0.83), valoracion)
        velocidad_regate = random.randint(round(valoracion * 0.83), valoracion)
        precision_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 2)
        velocidad_pase_corto = random.randint(round(valoracion * 0.9), valoracion + 2)
        precision_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 5)
        velocidad_pase_largo = random.randint(round(valoracion * 0.9), valoracion + 5)
        precision_disparo = random.randint(round(valoracion * 0.85), valoracion - 6)
        potencia_disparo = random.randint(round(valoracion * 0.85), valoracion - 6)
        tecnica_disparo = random.randint(round(valoracion * 0.87), valoracion - 2)
        tiros_libres = random.randint(round(valoracion * 0.8), valoracion - 3)
        efecto = random.randint(round(valoracion * 0.9), valoracion - 3)
        cabezazo = random.randint(round(valoracion * 0.7), round(valoracion * 0.9))        
        salto = random.randint(round(valoracion * 0.7), round(valoracion * 0.9))    
        tecnica = random.randint(round(valoracion * 0.85), valoracion + 2)
        agresividad = random.randint(round(valoracion * 0.88), valoracion - 4)
        mentalidad = random.randint(round(valoracion * 0.7), valoracion + 6)
        cualidades_portero = 30
        trabajo_en_equipo = round(valoracion * 0.9)
        estabilidad_soltura = random.randint(4,8)
        precision_pie_malo = random.randint(1,8)
        frecuencia_pie_malo = random.randint(1,8)
    elif posicion == "DEF":
        ataque = round(valoracion * 0.2)
        velocidad = round(valoracion * 0.5)
        regate = round(valoracion * 0.3)
        defensa = round(valoracion * 0.9)
    elif posicion == "POR":
        ataque = round(valoracion * 0.1)
        velocidad = round(valoracion * 0.3)
        regate = round(valoracion * 0.1)
        defensa = round(valoracion * 0.9)
    else:
        # Otras posiciones
        ataque = round(valoracion * 0.5)
        velocidad = round(valoracion * 0.5)
        regate = round(valoracion * 0.5)
        defensa = round(valoracion * 0.5)

    return f"Ataque: {ataque}\nDefensa: {defensa}\nEstabilidad: {estabilidad}\nResistencia: {resistencia}\nAgilidad: {agilidad}\nVelocidad Máxima: {velocidad_maxima}\nAceleración: {aceleracion}\nRespuesta: {respuesta}\nPrecisión Regate: {precision_regate}\nVelocidad Regate: {velocidad_regate}\nPrecisión Pase Corto: {precision_pase_corto}\nVelocidad Pase Corto: {velocidad_pase_corto}\nPrecisión Pase Largo: {precision_pase_largo}\nVelocidad Pase Largo: {velocidad_pase_largo}\nPrecisión Disparo: {precision_disparo}\nPotencia Disparo: {potencia_disparo}\nTécnica Disparo: {tecnica_disparo}\nTiros Libres: {tiros_libres}\nEfecto: {efecto}\nCabezazo: {cabezazo}\nSalto: {salto}\nTécnica: {tecnica}\nAgresividad: {agresividad}\nMentalidad: {mentalidad}\nCualidades Portero: {cualidades_portero}\nTrabajo en Equipo: {trabajo_en_equipo}\nEstabilidad (Soltura): {estabilidad_soltura}\nPrecisión Pie Malo: {precision_pie_malo}\nFrecuencia Pie Malo: {frecuencia_pie_malo}"


def mostrar_resultados():
    valoracion = int(entry_valoracion.get())
    posicion = combo_posicion.get()
    
    resultado = calcular_estadisticas(valoracion, posicion)
    
    # Muestra los resultados en la etiqueta de salida
    resultado_label.config(text=resultado)

def guardar_resultados():
    valoracion = int(entry_valoracion.get())
    posicion = combo_posicion.get()
    
    resultado = calcular_estadisticas(valoracion, posicion)
    
    # Abre el cuadro de diálogo para guardar el archivo
    file_path = filedialog.asksaveasfilename(defaultextension=".txt", filetypes=[("Archivos de texto", "*.txt")])
    
    if file_path:
        # Guarda las estadísticas en el archivo seleccionado
        with open(file_path, "w") as file:
            file.write(resultado)
            tk.messagebox.showinfo("Guardado", "Estadísticas guardadas correctamente.")

# Crear la ventana principal
ventana = tk.Tk()
ventana.title("Calculadora de Estadísticas de Jugadores de Fútbol")

# Crear estilo ttk
style = ttk.Style()
style.theme_use('clam')
style.configure("TButton", padding=6, relief="flat", background="#b1dcfb")
style.configure("TLabel", background="#e0f3ff")
style.configure("TEntry", padding=6, relief="flat", background="#ffffff")

# Crear widgets
label_valoracion = ttk.Label(ventana, text="Valoración Global:")
entry_valoracion = ttk.Entry(ventana)

label_posicion = ttk.Label(ventana, text="Posición:")
posiciones = ["DEL", "EXT", "MP", "MC", "CAR", "MCD", "LAT", "DEF", "POR", "Otro"]
combo_posicion = tk.StringVar()
combo_posicion.set(posiciones[0])
combo_posicion_menu = ttk.Combobox(ventana, textvariable=combo_posicion, values=posiciones)

boton_calcular = ttk.Button(ventana, text="Calcular", command=mostrar_resultados)
boton_guardar = ttk.Button(ventana, text="Guardar", command=guardar_resultados)

resultado_label = ttk.Label(ventana, text="Resultados aquí", justify="left")

# Colocar widgets en la ventana
label_valoracion.grid(row=0, column=0, padx=10, pady=10)
entry_valoracion.grid(row=0, column=1, padx=10, pady=10)
label_posicion.grid(row=1, column=0, padx=10, pady=10)
combo_posicion_menu.grid(row=1, column=1, padx=10, pady=10)
boton_calcular.grid(row=2, column=0, pady=10)
boton_guardar.grid(row=2, column=1, pady=10)
resultado_label.grid(row=3, column=0, columnspan=2, pady=10)

# Iniciar el bucle principal
ventana.mainloop()